### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by SteveGillespie** [matrixds/tools#11]
It appears that you can only download files (at least from the file menu) if you are the owner of a project, not if you are a contributor (even with write permissions).  

Also, there is no option to download entire directories.  You can export an arbitrary directories, however, using R Studio's export option.

**Comment by isaacfab** [comment]
within RStudio and Jupyterlab you need to zip the directory before downloading it. Adding downloading by contributors is now added to the feature backlog.
