### ISSUE TITLE
Issues with Simultaneous Tool Use

### ISSUE THREAD

**Issue by SteveGillespie** [matrixds/tools#12]
Matrix seems to be having an issue where two users on the same project cannot work on the same tool simultaneously.  For example, a colleague and I are working on a project and when I open up R Studio, it opens up his instance of R - to include files I'm not working on nor have ever opened.

**Comment by isaacfab** [comment]
RStudio and Jupyterlab create a few files that it uses to keep track of user preferences and state. If these files are in the shared project folder (which they are by default) all users will have the same settings. Changing these settings within individual tools can prevent this.
