### ISSUE TITLE
All files disappeared

### ISSUE THREAD

**Issue by sfp23** [matrixds/tools#14]
I have been using MatrixDS for an ongoing project, and my code files have all disappeared. The project itself no longer shows up on my dashboard, but I was able to find it by following a link in my history (https://community.platform.matrixds.com/sarahfpoole/painproject/dashboard), however my code is no longer saved here. I obviously would like this to be corrected and to have my code made available again.

**Comment by isaacfab** [comment]
The community site has been restricted. Please contact alejandro@matrixds.com about recovering files.
