### ISSUE TITLE
Can't add a new tool

### ISSUE THREAD

**Issue by atehranchi** [matrixds/tools#2]
Button disappears

**Comment by isaacfab** [comment]
Is this inside a project or the admin new tools page?

**Comment by atehranchi** [comment]
A few issues:

1. after logging in at mammoth.platform.matrixds.com, I get kicked off randomly.
2. Inside a project, the dashboard doesn't show up. 
3. In tools tab, there is no green button to start a new tool. 
4. Clicking on the Settings tab kicks me off and window must be reopened.

**Comment by isaacfab** [comment]
Got it. We are looking into it now.

**Comment by isaacfab** [comment]
For 1,2 and 4 we have pushed bug fixes. For 3 you must be a 'contributor' on a project in order to add tools. Likely your status is set (by the project owner) as a viewer.

I am closing this issue.
