### ISSUE TITLE
Button DELETE PROJECT doesn't work.

### ISSUE THREAD

**Issue by mruanova** [matrixds/tools#20]
While trying to work on my assignments I forklifted the project more than three times, 
then I tried to delete the ones that I am no longer using.
But they are still there:

https://codingdojo.platform.matrixds.com/mruanova/data-science-mau/settings

https://codingdojo.platform.matrixds.com/mruanova/data-science-plus-mau/settings

**Comment by byronslee** [comment]
Hi
The database shows you have 6 current projects and 5 deleted projects, so it seems like the delete is working for you some of the time.  Are you still having problems deleting projects?  If you are it will help if you can give the URL for the ones you want to delete, I am not sure if the above are the ones you want to delete since other projects have names like "test" and "test-mau".

**Comment by mruanova** [comment]
DELETE https://codingdojo.platform.matrixds.com/mruanova/data-science-mau/
DELETE https://codingdojo.platform.matrixds.com/mruanova/data-science-plus-mau/
DELETE https://codingdojo.platform.matrixds.com/mruanova/test/

KEEP https://codingdojo.platform.matrixds.com/mruanova/data-science-plus-prereq1599675097647/
KEEP https://codingdojo.platform.matrixds.com/mruanova/test-mau/
KEEP https://codingdojo.platform.matrixds.com/mruanova/ds-plus-mau/

**Comment by byronslee** [comment]
Please confirm you see 6 projects:  the 3 you mention above you want to keep and:  "linear -algebra", "the-birthday-problem",  and then 1 of the 3 projects you wanted to delete:  "data-science-plus-mau".  I show  "data-science-mau" and "test" as already Deleted, so you should no longer see them.

What symptoms did you experience when you tried to delete the projects?  I seems to have worked for you 2 of the 3 times for  "data-science-mau" and "test", and you have deleted a total of 5 projects overall.  We have not generally seen problems with delete, but there can be some delay in getting confirmation from the infrastructure that the delete occurred.  Usually waiting 5 mins or so and refreshing the browser fixes those, and they occur rarely.

**Comment by mruanova** [comment]
Form what I understand, after I delete the project you are still able to see it and I am no able to create it again with the same name, so the delete is not a true delete. That is not how repositories work on GitHub, I would like to be able to completely delete it and i create again with the same name, but whatever.
