### ISSUE TITLE
Button START is disabled.

### ISSUE THREAD

**Issue by mruanova** [matrixds/tools#21]
After successfully forklifting my project and being able to see the files,
I cannot start the project or run the jupyter notebooks.
I looked in every tab.
Seems like I have permissions to VIEW ONLY.
![Screen Shot 2020-09-21 at 9 20 00 AM](https://user-images.githubusercontent.com/15058177/93778864-f5538800-fbeb-11ea-87ba-837b8d832e04.png)
Work Around: I will continue working locally using ANACONDA and uploading the file to learn.codingdojo.com

**Comment by byronslee** [comment]
Hi
The image posted is of the list of your projects.  You then go into a project by clicking on  the name either from the cards or from the list.  When you are in the project view, there is a tools section where you can create or start the tools, such as the jupyter notebook.   If you are having trouble getting into a project or have problems with the project view, please let me know.   Byron

**Comment by mruanova** [comment]
I clicked on the card, and went through each of the tabs, I know I have seen the START button last week, but since yesterday or so, I just don't see the START button anymore. I believe I don't have permissions.

**Comment by byronslee** [comment]
Let me explain how the permissions work:  they are tied to project sharing.
The projects page lists all the projects you can see, and the table shows if you are the owner, a contributor or a user.   

If you are an owner, you can create, start, stop and delete tools:  these would be projects you create from scratch and projects that you forklift.    If you have shared your project with someone where they are a contributor, they can create their own tools:  you can see but not modify their PRESENT category of tools. 

If you are a contributor on a project owned by someone else, you can likewise see their PRESENT tools but not modify them.  You can create your own tools for their project, which you can start, stop and delete.

If you are a user on a project owned by someone else, you can only see PRESENT tools created by other people, you can not modify them at all.

Any tools that you create yourself, you have permission to Start, Stop and Delete.   When you are looking at tools from someone else (only the PRESENT tools are visible to other people), that is when you can not start, stop or delete them.  For projects you created yourself (from scratch or from forklifting) you have full control of all tools, except ones from any collaborators you have added to the project.   As a collaborator, you can only control the tools you have created.

You might find it helpful to put something in the names or descriptions to help you remember which projects and tools you own.  Projects shared between multiple people can have multiple copies of the same tool, each owned by the different collaborators.   This gives a lot of flexibility and helps people work together, but it can be helpful to have a quick way of remembering which are the ones you created.    

If you are still having trouble, then please send me the URL for the project and tools or screenshots so I can research further.

Byron

**Comment by mruanova** [comment]
ok my bad, turns out that the STOP button in the server instance that was running didn't stop the instance, so i deleted the instance, and that is why i couldn't see the card in the TOOLS tab, but i was able to create a new one and start it.
