### ISSUE TITLE
Tools Tab Is not Active

### ISSUE THREAD

**Issue by BongekaZ** [matrixds/tools#6]
My Tools Tab does not seem to be active. I can't see the code used for the project... it's supposed to show the R code but it doesn't. See screenshot below.

![Screen Shot 2019-05-15 at 3 03 24 PM](https://user-images.githubusercontent.com/50681473/57812786-eec51e80-7722-11e9-9c07-f1b6e70fd457.png)

**Comment by isaacfab** [comment]
The reason you can not create tools on this tab is, likely because you are a 'viewer' have the project owner change you to an 'editor'

**Comment by isaacfab** [comment]
I think this was taken care of.

**Comment by BongekaZ** [comment]
Thank you so much. Will try this!
