### ISSUE TITLE
git integrations

### ISSUE THREAD

**Issue by lensonp** [matrixds/tools#8]
Not sure if this is in the pipeline already or not, but integrating git into your platform would enable many projects to migrate in, and more importantly, would greatly increase your platform's viability for developers.

**Comment by isaacfab** [comment]
We have several git features on our dev pipeline for the next version. For now, there is a git client that runs in the background (versioning all of the code files). You can also initialize or clone a repo into a project using the terminal from within the munge tools (like Jupyterlab or RStudio). Thanks for the feedback! Information on the automated system can be found here: http://userguide.matrixds.com/versions.html
