### ISSUE TITLE
Unable to accept project I've been invited to collaborate in

### ISSUE THREAD

**Issue by BongekaZ** [matrixds/tools#9]
![Screen Shot 2019-08-04 at 1 24 11 PM](https://user-images.githubusercontent.com/50681473/62428890-d4fcfd00-b6bb-11e9-9c14-73ffb5e2a982.png)
I was invited to collaborate on a project but each time I click on the link and try to access the project, my screen remains on the login page and does not progress to the project even after I have put in my log in information.

**Comment by isaacfab** [comment]
Thanks for submitting the bug! If you click on the projects link on the top left of the page you should get the project view. We will get on the redirect issues ASAP.

**Comment by BongekaZ** [comment]
I have tried to do that but the project I was invited to join does not show up on.
